// auto generated by configure
#ifndef SRS_AUTO_HEADER_HPP
#define SRS_AUTO_HEADER_HPP

#define SRS_PACKAGER ""
#define SRS_BUILD_TS "1654596283"
#define SRS_BUILD_DATE "2022-06-07 17:04:43"
#define SRS_UNAME "Linux wrapper-VivoBook-14-ASUS-Laptop-X407UF 5.15.0-33-generic #34-Ubuntu SMP Wed May 18 13:34:26 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux"
#define SRS_USER_CONFIGURE "--x86-x64 --ffmpeg-fit=off"
#define SRS_CONFIGURE "--prefix=/usr/local/srs --config=conf/srs.conf --hls=on --hds=off --dvr=on --ssl=on --https=on --ssl-1-0=off --ssl-local=off --sys-ssl=off --transcode=on --ingest=on --stat=on --http-callback=on --http-server=on --stream-caster=on --http-api=on --utest=off --cherrypy=off --srt=off --rtc=on --simulator=off --cxx11=off --cxx14=off --ffmpeg-fit=off --nasm=on --srtp-nasm=on --clean=on --gperf=off --gmc=off --gmd=off --gmp=off --gcp=off --gprof=off --static=off --shared-st=off --shared-srt=off --shared-ffmpeg=off --log-verbose=off --log-info=off --log-trace=on --gcov=off --debug=off --debug-stats=off --cross-build=off --cc=gcc --cxx=g++ --ar=ar --ld=ld --randlib=randlib"

#undef SRS_HDS
#define SRS_HDS_BOOL false
#undef SRS_SRT
#define SRS_SRT_BOOL false
#undef SRS_CXX11
#define SRS_CXX11_BOOL false
#undef SRS_CXX14
#define SRS_CXX14_BOOL false
#define SRS_RTC
#define SRS_RTC_BOOL true
#undef SRS_FFMPEG_FIT
#define SRS_FFMPEG_FIT_BOOL false
#undef SRS_SIMULATOR
#define SRS_SIMULATOR_BOOL false
#define SRS_HTTPS
#define SRS_HTTPS_BOOL true
#undef SRS_UTEST
#define SRS_UTEST_BOOL false
#define SRS_FFMPEG_STUB
#define SRS_FFMPEG_STUB_BOOL true
#undef SRS_GPERF
#define SRS_GPERF_BOOL false
#undef SRS_GPERF_MC
#define SRS_GPERF_MC_BOOL false
#undef SRS_GPERF_MD
#define SRS_GPERF_MD_BOOL false
#undef SRS_GPERF_MP
#define SRS_GPERF_MP_BOOL false
#undef SRS_GPERF_CP
#define SRS_GPERF_CP_BOOL false
#undef SRS_VERBOSE
#define SRS_VERBOSE_BOOL false
#undef SRS_INFO
#define SRS_INFO_BOOL false
#define SRS_TRACE
#define SRS_TRACE_BOOL true
#undef SRS_CROSSBUILD
#define SRS_CROSSBUILD_BOOL false
#undef SRS_OSX
#define SRS_OSX_BOOL false
#undef SRS_DEBUG
#define SRS_DEBUG_BOOL false
#undef SRS_DEBUG_STATS
#define SRS_DEBUG_STATS_BOOL false

#define SRS_PREFIX "/usr/local/srs"
#define SRS_DEFAULT_CONFIG "conf/srs.conf"

#define SRS_CONSTRIBUTORS "\
Winlin<winlin@vip.126.com> \
Winlin<winterserver@126.com> \
Winlin<chengli.ycl@alibaba-inc.com> \
Wenjie<zhaowenjie@tal.com> \
Wenjie<740936897@qq.com> \
Wenjie<wenjie.zhao@chinacache.com> \
xiangcheng.liu<liuxc0116@foxmail.com> \
naijia.liu<youngcow@youngcow.net> \
alcoholyi<alcoholyi@qq.com> \
byteman<wangchen2011@gmail.com> \
chad.wang<chad.wang.cn@gmail.com> \
suhetao<suhetao@gmail.com> \
Johnny<fengjihu@163.com> \
karthikeyan<keyanmca@gmail.com> \
StevenLiu<lq@chinaffmpeg.org> \
zhengfl<zhengfl_1989@126.com> \
tufang14<breadbean1449@gmail.com> \
allspace<allspace@gmail.com> \
niesongsong<nie950@gmail.com> \
rudeb0t<nimrod@themanxgroup.tw> \
CallMeNP<np.liamg@gmail.com> \
synote<synote@qq.com> \
lovecat<littlefawn@163.com> \
panda1986<542638787@qq.com> \
YueHonghui<hongf.yue@hotmail.com> \
ThomasDreibholz<dreibh@simula.no> \
JuntaoLiu<juntliu@gmail.com> \
RocFang<fangpeng1986@gmail.com> \
MakarovYaroslav<yaroslav.makarov.97@mail.ru> \
MirkoVelic<mvelic@inoxx.net> \
HuiZhang(huzhang2)<huzhang2@cisco.com> \
OtterWa<simpleotter23@gmail.com> \
walkermi<172192667@qq.com> \
haofz<fuzhuang.hao@vhall.com> \
ME_Kun_Han<hanvskun@hotmail.com> \
ljx0305<ljx0305@gmail.com> \
cenxinwei<censhanhe@163.com> \
StarBrilliant<m13253@hotmail.com> \
xubin<xubin@chnvideo.com> \
intliang<yintiliang@gmail.com> \
flowerwrong<sysuyangkang@gmail.com> \
YLX<568414379@qq.com> \
J<guotaojiang@qq.com> \
Harlan<hailiang@gvrcraft.com> \
hankun<hankun@bravovcloud.com> \
JonathanBarratt<jonathan.barratt@gmail.com> \
KeeganH<keeganwharris@gmail.com> \
StevenLiu<lingjiujianke@gmail.com> \
liuxc0116<liuxc0116@gmail.com> \
ChengdongZhang<lmajzcd@sina.com> \
lovacat<lovecat@china.sina.com> \
qiang.li<qiang.li@verycdn.com.cn> \
HungMingWu<u9089000@gmail.com> \
Himer<xishizhaohua@qq.com> \
XiaLixin<xialixin@kanzhun.com> \
XiaLixin<68469352@qq.com> \
XiaLixin<xlx0625@163.com> \
XiaLixin<xialx@yuntongxun.com> \
alphonsetai<tyh_123@163.com> \
Michael.Ma<wnpllr@gmail.com> \
lam2003<linmin3@yy.com> \
ShiWei<shiwei05@kuaishou.com> \
ShiWei<shi.weibd@hotmail.com> \
XiaofengWang<wasphin@gmail.com> \
XiaoZhihong<hondaxiao@tencent.com> \
XiaoZhihong<xiaozhihong8@gmail.com> \
XiaoZhihong<xiaozhihong@huya.com> \
yanghuiwen<cainiaodj@qq.com> \
WuPengqiang<309554135@qq.com> \
WuPengqiang<pengqiang.wpq@alibaba-inc.com> \
l<22312935+lam2003@github> \
xfalcon<x-falcon@github> \
ChenGuanghua<jinxue.cgh@alibaba-inc.com> \
ChenGuanghua<chengh_math@126.com> \
LiPeng<mozhan.lp@alibaba-inc.com> \
LiPeng<lipeng19811218@gmail.com> \
yajun18<yajun18@staff.sina.com.cn> \
liulichuan<liulichuan@kuaishou.com> \
yapingcat<caoyapingneu@163.com> \
chenchengbin<chenchengbin@yy.com> \
ChenHaibo<495810242@qq.com> \
ChenHaibo<nmgchenhaibo@foxmail.com> \
jasongwq<jasongwq@gmail.com> \
yinjiaoyuan<yinjiaoyuan@163.com> \
PieerePi<pihuibin@hotmail.com> \
JesseXi<jesse.jinjin@wo.cn> \
PieerePi<40780488+PieerePi@github> \
ghostsf<ghost_sf@163.com> \
xbpeng121<53243357+xbpeng121@github> \
johzzy<hellojinqiang@gmail.com> \
stone<bluestn@163.com> \
cfw11<34058899+cfw11@github> \
Hung-YiChen<gaod.chen@gmail.com> \
long<liyalong12345@126.com> \
matthew1838<77285055+matthew1838@github> \
rise<rise.worlds@outlook.com> \
"

#endif

